[build]
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
preDeployCommand = "python manage.py migrate && python manage.py create_superuser_auto"
startCommand = "gunicorn gfood.wsgi --bind 0.0.0.0:${PORT:-8000}"
