# Generated by Django 6.0.3 on 2026-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Customer ID'),
        ),
    ]
