# Generated by Django 5.2.12 on 2026-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origem',
            field=models.CharField(choices=[('app', 'App (Cliente)'), ('caixa', 'Caixa (Presencial)')], default='app', max_length=10, verbose_name='Origem'),
        ),
    ]
