# Generated by Django 5.2.12 on 2026-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_transaction_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='card',
            name='motivo_bloqueio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do Bloqueio'),
        ),
    ]
