# Generated by Django 5.2.12 on 2026-04-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_bloqueado_card_motivo_bloqueio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Cliente'),
        ),
    ]
