# Generated by Django 5.2.12 on 2026-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
    ]
