# Generated by Django 5.2.12 on 2026-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem (Base64)'),
        ),
    ]
